SICOS/SICOS/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, re_path, include
from django.contrib.auth.decorators import login_required

from facturacion.views import * 
from cirugia.views import *
from solicitud.views import *
from django.conf import settings
from django.views.static import serve

from django.conf.urls import handler404

# apis
from solicitud.api import UserAPI


# handler404 = mi_error_404


# from django.contrib.auth.decorators import login, logout_then_login

urlpatterns = [
    #VISTA DE ADMINSTRADOR
    path('admin/', admin.site.urls),
    path('solicitud/', include('solicitud.urls')),

    
    #LOGIN
    path('',LoginView.as_view(template_name= 'Entrada/login.html'), name ='login'),
    #LOGOUT
    path('logout/',LogoutView.as_view(), name ='logout'),



    #ENVIAR EMAIL
    path('EnviarMailAuto/',EnviarMailAuto, name ='EnviarMailAuto'),
    path('Mail_list/',Mail_list, name ='Mail_list'),


    path('convertirpdf/',convertirpdf, name ='convertirpdf'),

    
    #REPORTES  EN EXCEL
    #arriendos
    path('report_arriendo_excel/',Reporte_arriendo_excel.as_view(), name ='report_arriendo_excel'),
    #especialistas
    path('report_especialista_excel/',Reporte_especialista_excel.as_view(), name ='report_especialista_excel'),
    #SendMail
    path('report_SendMail_excel/',Reporte_SendMail_excel.as_view(), name ='report_SendMail_excel'),
    
    
    #PAGINA PRINCIPAL
    path('home', login_required(index), name='home'),

    path('cpp/', login_required(base), name='base'),
    path('cirugia/', login_required(base_cirugia), name='base_cirugia'),
    path('solicitudes/', login_required(base_solicitud), name='base_solicitud'),

    path('cambiar_pass_form/', login_required(cambiar_pass_form), name='cambiar_pass_form'),
    path('cambiar_pass_form_error/', login_required(cambiar_pass_form_error), name='cambiar_pass_form_error'),
    path('cambiar_pass/', login_required(cambiar_pass), name='cambiar_pass'),

    
    
    #REPORTES EN PDF
    #arriendos
    path('reporteCPP/<int:id_>/',login_required(Reporte_CppArriendo_Pdf),name='reporteCPP'),
    #especialistas
    path('reporte_pdf_esp/<int:id_>/',login_required(Reporte_CppEspecialista_Pdf),name='reporte_pdf_esp'),
    #proveedores
    path('reporte_pdf_proveedores/<int:id_>/',login_required(Reporte_Proveedor_Pdf),name='reporte_pdf_provedores'),
    #servicios
    path('reporte_pdf_servicios/<int:id_>/',login_required(Reporte_servicios_Pdf),name='reporte_pdf_servicios'),













    #CIRUGIA=============================================================================================================
    path('Reporte_salario_excel/',Reporte_salario_excel.as_view(), name ='Reporte_salario_excel'),
    path('report_honorario_excel/',Reporte_Honorarios_excel.as_view(), name ='Reporte_honor_excel'),
    path('Reporte_consolidado_excel/',Reporte_Consolidado_excel.as_view(), name ='Reporte_consolidado_excel'),
    path('report_proc_excel/',Reporte_Proc_excel.as_view(), name ='Reporte_proc_excel'),
    path('Reporte_Canasta_excel/',Reporte_Canasta_excel.as_view(), name ='Reporte_Canasta_excel'),
    
    #CONSULTA INFORMACION
    path('consulta-procedimiento/',login_required(consulta_info), name ='consulta_info'),
    path('limpiar_consulta/',login_required(limpiar_consulta), name ='limpiar_consulta'),
    path('consulta-lista-proc/', login_required(data_proc_url), name='lista_proc_ajax'),
 
    #tipo_proc
    path('creartipo_proc/',login_required(tipo_procCrear.as_view()), name='tipo_proc_view'),
    path('listtipo_proc/',login_required(tipo_proc_list), name='tipo_proc_list'),
    path('edittipo_proc/<int:id_>/', login_required(tipo_procEdit), name='tipo_proc_edit'),
    path('elimtipo_proc/<int:id_>/', login_required(tipo_procElim), name='tipo_proc_elim'),

    #procedimiento
    path('crearprocedimiento/',login_required(procedimientoCrear.as_view()), name='procedimiento_view'),
    path('listprocedimiento/',login_required(procedimiento_list), name='procedimiento_list'),
    path('editprocedimiento/<int:id_>/', login_required(procedimientoEdit), name='procedimiento_edit'),
    path('elimprocedimiento/<int:id_>/', login_required(procedimientoElim), name='procedimiento_elim'),

    #concepto_honorario
    path('crearconcepto_honorario/',login_required(concepto_honorarioCrear.as_view()), name='concepto_honorario_view'),
    path('listconcepto_honorario/',login_required(concepto_honorario_list), name='concepto_honorario_list'),
    path('editconcepto_honorario/<int:id_>/', login_required(concepto_honorarioEdit), name='concepto_honorario_edit'),
    path('elimconcepto_honorario/<int:id_>/', login_required(concepto_honorarioElim), name='concepto_honorario_elim'),

    #nombre_canasta
    path('crearnombre_canasta/',login_required(nombre_canastaCrear.as_view()), name='nombre_canasta_view'),
    path('listnombre_canasta/',login_required(nombre_canasta_list), name='nombre_canasta_list'),
    path('editnombre_canasta/<int:id_>/', login_required(nombre_canastaEdit), name='nombre_canasta_edit'),
    path('elimnombre_canasta/<int:id_>/', login_required(nombre_canastaElim), name='nombre_canasta_elim'),

    #concepto_canasta
    path('crearconcepto_canasta/',login_required(concepto_canastaCrear.as_view()), name='concepto_canasta_view'),
    path('listconcepto_canasta/',login_required(concepto_canasta_list), name='concepto_canasta_list'),
    path('editconcepto_canasta/<int:id_>/', login_required(concepto_canastaEdit), name='concepto_canasta_edit'),
    path('elimconcepto_canasta/<int:id_>/', login_required(concepto_canastaElim), name='concepto_canasta_elim'),

    #position
    path('crearposition/',login_required(positionCrear.as_view()), name='position_view'),
    path('listposition/',login_required(position_list), name='position_list'),
    path('editposition/<int:id_>/', login_required(positionEdit), name='position_edit'),
    path('elimposition/<int:id_>/', login_required(positionElim), name='position_elim'),

    #canasta
    path('crearcanasta/',login_required(canastaCrear), name='canasta_view'),
    path('listcanasta/',login_required(canasta_list), name='canasta_list'),
    path('editcanasta/<int:id_>/', login_required(canastaEdit), name='canasta_edit'),
    path('elimcanasta/<int:id_>/', login_required(canastaElim), name='canasta_elim'),

    #honorario
    path('crearhonorario/',login_required(honorarioCrear.as_view()), name='honorario_view'),
    path('listhonorario/',login_required(honorario_list), name='honorario_list'),
    path('edithonorario/<int:id_>/', login_required(honorarioEdit), name='honorario_edit'),
    path('elimhonorario/<int:id_>/', login_required(honorarioElim), name='honorario_elim'),

    #constante
    path('crearconstante/',login_required(constanteCrear.as_view()), name='constante_view'),
    path('listconstante/',login_required(constante_list), name='constante_list'),
    path('editconstante/<int:id_>/', login_required(constanteEdit), name='constante_edit'),
    path('elimconstante/<int:id_>/', login_required(constanteElim), name='constante_elim'),
   
    #concepto_salario
    path('crearconcepto_salario/',login_required(concepto_salarioCrear.as_view()), name='concepto_salario_view'),
    path('listconcepto_salario/',login_required(concepto_salario_list), name='concepto_salario_list'),
    path('editconcepto_salario/<int:id_>/', login_required(concepto_salarioEdit), name='concepto_salario_edit'),
    path('elimconcepto_salario/<int:id_>/', login_required(concepto_salarioElim), name='concepto_salario_elim'),

    # estancia
    path('crearestancia/',login_required(estanciaCrear.as_view()), name='estancia_view'),
    path('listestancia/',login_required(estancia_list), name='estancia_list'),
    path('editestancia/<int:id_>/', login_required(estanciaEdit), name='estancia_edit'),
    path('elimestancia/<int:id_>/', login_required(estanciaElim), name='estancia_elim'),
    
    # Tipo Estancia
    path('creartipo_estancia/',login_required(tipo_estanciaCrear.as_view()), name='tipo_estancia_view'),
    path('listtipo_estancia/',login_required(tipo_estancia_list), name='tipo_estancia_list'),
    path('edittipo_estancia/<int:id_>/', login_required(tipo_estanciaEdit), name='tipo_estancia_edit'),
    path('elimtipo_estancia/<int:id_>/', login_required(tipo_estanciaElim), name='tipo_estancia_elim'),

    #salario
    path('crearsalario/',login_required(salarioCrear.as_view()), name='salario_view'),
    path('listsalario/',login_required(salario_list), name='salario_list'),
    path('editsalario/<int:id_>/', login_required(salarioEdit), name='salario_edit'),
    path('elimsalario/<int:id_>/', login_required(salarioElim), name='salario_elim'),

    










    #CONTRATO
    path('crearcontrato/',login_required(contratoCrear.as_view()), name='contrato_view'),
    path('listcontrato/',login_required(contrato_list), name='contrato_list'),
    path('editcontrato/<int:pk>/', login_required(contratoEditar.as_view()), name='contrato_edit'),

    #TARIFA
    path('creartarifa/',login_required(tarifaCrear.as_view()), name='tarifa_view'),
    path('listtarifa/',login_required(tarifa_list), name='tarifa_list'),
    path('edittarifa/<int:pk>/', login_required(tarifaEdit.as_view()), name='tarifa_edit'),


    #UVT
    path('crearuvt/',login_required(uvtCrear.as_view()), name='uvt_view'),
    path('listuvt/',login_required(uvt_list), name='uvt_list'),
    path('edituvt/<int:pk>/', login_required(uvtEditar.as_view()), name='uvt_edit'),

    #RETEN_383
    path('crearreten_383/',login_required(reten_383Crear.as_view()), name='reten_383_view'),
    path('listreten_383/',login_required(reten_383_list), name='reten_383_list'),
    path('editreten_383/<int:pk>/', login_required(reten_383Editar.as_view()), name='reten_383_edit'),


    #RETENCION
    path('crearretencion/',login_required(retencionCrear.as_view()), name='retencion_view'),

SICOS/cirugia/models.py
from django.db import models

# Create your models here.
class tipo_proc(models.Model):
    nombre_tipo_proc = models.CharField('Nombre de la Especialidad', null = True, max_length = 80)
    # archivo = models.FileField(blank = True, null= True, upload_to ="chapters/%Y/%m/%D/")
    
    def __str__(self):
        return '%s' % (self.nombre_tipo_proc)
    
    class Meta:
        ordering = ['nombre_tipo_proc']

class nombre_canasta(models.Model):
    nombre_canasta = models.CharField('Nombre de la Canasta', null = True, max_length = 85)
    
    def __str__(self):
        return '%s' % (self.nombre_canasta)
    
    class Meta:
        ordering = ['nombre_canasta']

class procedimiento(models.Model):
    cod = models.CharField('Código', null = True, max_length = 20, blank = True)
    tipo_proc = models.ForeignKey(tipo_proc,verbose_name = 'Especialidad', null = True, on_delete=models.CASCADE)
    nombre_proc = models.CharField('Nombre del Procedimiento', null = True, max_length = 190)
    nombre_canasta = models.ForeignKey(nombre_canasta,verbose_name = 'Canasta', null = True, on_delete=models.CASCADE)
    duracion_proc = models.FloatField('Duración en minutos', null = True)
    uvr =  models.FloatField('UVR', null = True, blank = True, default = 0)
    dias_estancia = models.IntegerField('Días Estancia', null = True, default = 0)
    
    def __str__(self):
        return '%s' % (self.nombre_proc)
    
class concepto_honorario(models.Model):
    nombre_concep_hon = models.CharField('Nombre del Concepto', null = True, max_length = 30)
    
    def __str__(self):
        return '%s' % (self.nombre_concep_hon)
    
    class Meta:
        ordering = ['nombre_concep_hon']

class concepto_canasta(models.Model):
    nombre_canasta = models.CharField('Concepto de la Canasta', null = True, max_length = 85)
    
    def __str__(self):
        return '%s' % (self.nombre_canasta)
    
    class Meta:
        ordering = ['nombre_canasta']

class position(models.Model):#aqui se escribe a q actividad pertenece el salario (entrada, ciruria, postcirugia, salida , etc)
    nombre_act = models.CharField('Nombre de la Actividad', null = True, max_length = 20)
    
    def __str__(self):
        return '%s' % (self.nombre_act)
    
    class Meta:
        ordering = ['nombre_act']

class canasta(models.Model):
    # tipo_proc = models.ForeignKey(tipo_proc, verbose_name ='Especialidad', on_delete = models.CASCADE,  null = True, max_length = 50)
    nombre_canasta = models.ForeignKey(nombre_canasta, verbose_name ='Nombre de la Canasta', on_delete=models.CASCADE, null = True)
    concepto_canasta =   models.ForeignKey(concepto_canasta,verbose_name = 'Concepto', null = True, on_delete = models.CASCADE)
    position =  models.ForeignKey(position, verbose_name ='Ubicación', null = True,blank=True, max_length = 20, on_delete = models.CASCADE)
    nombre_insumo = models.CharField('Nombre Insumo', null = True, max_length = 120)
    presentacion  = models.CharField('Presentación', null = True, blank=True, max_length = 20)
    cantidad =  models.FloatField('Cantidad', null = True, default = 1)
    costo_und =  models.FloatField('Costo Unitario', null = True)
    costo_tot =  models.FloatField('Costo Subtotal', null = True, default=0)#este campo es calculado
   
class honorario(models.Model):
    tipo_proc = models.ForeignKey(tipo_proc,verbose_name = 'Especialidad', null = True, on_delete=models.CASCADE)
    procedimiento = models.ForeignKey(procedimiento,verbose_name = 'Nombre del Procedimiento', null = True, on_delete=models.CASCADE)
    nombre_canasta = models.ForeignKey(nombre_canasta,verbose_name = 'Canasta', null = True, on_delete=models.CASCADE)
    concepto_honorario = models.ForeignKey(concepto_honorario,verbose_name = 'Concepto', null = True, on_delete=models.CASCADE)
    # duracion = models.FloatField('Duración', null = True)
    # uvr =  models.FloatField('UVR', null = True)
    info = models.TextField('Información', null = True, blank =  True)
    costo = models.FloatField('Costo no Paramertrizado', null = True, blank = True, default=0)
    # subtotal = models.FloatField('Subtotal', null = True)
    
class constante(models.Model):
    iss_adicional = models.FloatField('Porcentaje Ganancia', null = True)
    valor_uvt = models.FloatField('Valor UVT Especialistas', null = True, default = 0)
    smdlv = models.FloatField('Salaraio Minimo Diario L.V.', null = True, default = 0)
    
    
    def __str__(self):
        return '%s' % (self.iss_adicional)
    
    class Meta:
        ordering = ['iss_adicional']
    
class concepto_salario(models.Model):
    nombre_concep_sal = models.CharField('Concepto', null = True, max_length = 30)
    
    def __str__(self):
        return '%s' % (self.nombre_concep_sal)
    
    class Meta:
        ordering = ['nombre_concep_sal']
    
class tipo_estancia(models.Model):
    nombre_tipo_est = models.CharField('Tipo de Estancia', null =  True, max_length = 60)
    numero_camas = models.IntegerField('Número de Camas', null =  True, default = 0)

    def __str__(self):
        return '%s' % (self.nombre_tipo_est)

class estancia(models.Model):
    tipo_estancia = models.ForeignKey(tipo_estancia, null=True, on_delete=models.CASCADE, verbose_name = "Tipo de Estancia")
    concepto_estancia = models.CharField('Concepto Estancia', null = True, max_length = 40)
    valor_concepto = models.FloatField('Valor día',null=True, default = 0)
    dividir_por_cama = models.BooleanField('¿Se divide entre el número de camas ?', default = True)
    
    def __str__(self):
        return '%s' % (self.concepto_estancia)

    
class salario(models.Model):
    tipo_proc = models.ForeignKey(tipo_proc,verbose_name = 'Tipo Procedimiento', null = True, on_delete=models.CASCADE)
    procedimiento = models.ForeignKey(procedimiento, verbose_name = 'Nombre del Procedimiento', null = True, on_delete = models.CASCADE)
    # nombre_canasta = models.ForeignKey(nombre_canasta,verbose_name = 'Canasta', null = True, on_delete=models.CASCADE)
    # rubro = models.ForeignKey(rubro,verbose_name = 'Rubro', null = True, on_delete=models.CASCADE)
    concepto_salario = models.ForeignKey(concepto_salario,verbose_name = 'Concepto', null = True, on_delete=models.CASCADE)
    position = models.ForeignKey(position,verbose_name = 'Ubicación Concepto', null = True, on_delete=models.CASCADE)
    # duracion = models.FloatField('Duración', null = True)
    costo = models.FloatField('Costo', null = True)
    # subtotal =  models.FloatField('Subtotal', null = True)


  
#este modelo es solo para consultar los procedimientos
class consulta(models.Model):
    tipo_proc = models.ForeignKey(tipo_proc,verbose_name = 'Tipo Procedimiento', null = True, on_delete=models.CASCADE)
    procedimiento = models.ForeignKey(procedimiento, verbose_name = 'Nombre del Procedimiento', null = True, on_delete = models.CASCADE)
    ganancia = models.FloatField('Ganancia', default = 0)

SICOS/templates/cirugia/canasta_list.html
{% extends 'base_cirugia.html' %}


{% block title %}
    Canasta
{% endblock title %}


{% block content %}

  <a class= "btn btn-success" href= "{% url 'canasta_view' %}" >Crear Canasta<ion-icon name="add"></ion-icon></a>
  <a class= "btn btn-success" onclick = "return DescargarConsolidado()" href= "{% url 'Reporte_Canasta_excel' %}" ><i class="fas fa-file-excel"></i> Exportar CANASTAS</a>


    <div class="card mb-3">
            <div class="card-header">
                    <i class="fas fa-table"></i>
                    Canasta
                  </div>
            
                    <!-- <form>
                      <input type="search" placeholder="AAAA-MM-DD" name="filtrofechacpp" aria-controls="dataTable">
                      <input type="search" placeholder="Código" name="filtroidcpp" aria-controls="dataTable">
                      <button type="submit" name="botonfiltrocpp">Filtrar</button>
                    </form> -->
                  {%if canastas %}
                  <div class="card-body">
                    <div class="table-wrapper-scroll-y my-custom-scrollbar table-responsive " >
                
                        <div class="row">
                          <div class=" col-sm-12"><table class="table table-bordered dataTable table-hover" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                            <thead>
                              <tr role="row">
                                <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Name: activate to sort column descending" style="width: 71px;" aria-sort="ascending"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Código</font></font></th>
                                <!-- <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Salary: activate to sort column ascending" style="width: 52px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Especialidad</font></font></th> -->
                                <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Salary: activate to sort column ascending" style="width: 52px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Nombre_de_la_Canasta</font></font></th>
                                <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Name: activate to sort column descending" style="width: 71px;" aria-sort="ascending"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Concepto</font></font></th>
                                <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Salary: activate to sort column ascending" style="width: 52px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Posición</font></font></th>
                                <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Salary: activate to sort column ascending" style="width: 52px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Nombre_Insumo </font></font></th>
                                <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Salary: activate to sort column ascending" style="width: 52px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Presentación </font></font></th>
                                <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Salary: activate to sort column ascending" style="width: 52px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Cantidad</font></font></th>
                                <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Salary: activate to sort column ascending" style="width: 52px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> Costo_Unitario</font></font></th>
                                <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Salary: activate to sort column ascending" style="width: 52px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Costo_Subtotal</font></font></th>
                                <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Salary: activate to sort column ascending" style="width: 52px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Acción</font></font></th>
                              </tr>
                            </thead>

                            <tbody>              
                        
                                {% for canasta in canastas %}  
                                <tr role="row" class="odd">
                                    <td class="sorting_1"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{canasta.id}}</font></font></td>
                                    <!-- <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{  canasta.tipo_proc}}</font></font></td> -->
                                    <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{  canasta.nombre_canasta}}</font></font></td>
                                    <td class="sorting_1"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{canasta.concepto_canasta}}</font></font></td>
                                    <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{  canasta.position}}</font></font></td>
                                    <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{  canasta.nombre_insumo}}</font></font></td>
                                    <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{  canasta.presentacion}}</font></font></td>
                                    <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{  canasta.cantidad}}</font></font></td>
                                    <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{  canasta.costo_und}}</font></font></td>
                                    <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{  canasta.costo_tot}}</font></font></td>
                                    <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> <center>
                                      <a class= "btn btn-primary btn-circle" href= "{% url 'canasta_edit' canasta.id%}" ><ion-icon name="create"></ion-icon></a>
                                      <a class= "btn btn-danger btn-circle" onclick = "return ElimRegistro()" href= "{% url 'canasta_elim' canasta.id%}" ><ion-icon name="trash"></ion-icon></a></center></font></font> 

                                    </td>
                                    
                                </tr>
                                {% endfor %}
                    
                {%else%}
                <div class="alert alert-dark" role="alert">
                    <h2>No hay Registros </h2>
                </div>
                    
                {% endif%}
                    
                                </tbody>
                          </table>
                          </div>
                      </div>
                    </div>
                  </div>
{% endblock content %}

SICOS/templates/cirugia/concepto_canasta_form.html
{% extends 'base_cirugia.html' %}


{% block title %}
    Concepto Canasta
{% endblock title %}


{% block content %}

  <div class="jumbotron" width=20%>
      <form method="post" > 
          {% csrf_token %}
          <table>
              {{form.as_table}}
          </table>
         
          <input type="submit" class="btn btn-info" value="Guardar">
          <a class="btn btn-danger" href="{% url 'concepto_canasta_list' %}">Cancelar</a>
      </form>
  </div>

{% endblock content %}

SICOS/templates/cirugia/concepto_honorario_form.html
{% extends 'base_cirugia.html' %}


{% block title %}
Concepto Honorario
{% endblock title %}


{% block content %}

  <div class="jumbotron" width=20%>
      <form method="post" > 
          {% csrf_token %}
          <table>
              {{form.as_table}}
          </table>
         
          <input type="submit" class="btn btn-info" value="Guardar">
          <a class="btn btn-danger" href="{% url 'concepto_honorario_list' %}">Cancelar</a>
      </form>
  </div>


  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <script>
      $("#id_tipo_proc").change(function () {
        var url = $("#consulta_infor_form").attr("data-proc-url");  // get the url of the `load_cities` view
        var tipo_procId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
          url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
          data: {
            'tipo_proc': tipo_procId       // add the country id to the GET parameters
          },
          success: function (data) {   // `data` is the return of the `load_cities` view function
            $("#id_procedimiento").html(data);  // replace the contents of the city input with the data that came from the server
          }
        });
      });
    </script>

{% endblock content %}

SICOS/templates/cirugia/concepto_salario_form.html
{% extends 'base_cirugia.html' %}


{% block title %}
    Concepto Salario
{% endblock title %}


{% block content %}

  <div class="jumbotron" width=20%>
      <form method="post" > 
          {% csrf_token %}
          <table>
              {{form.as_table}}
          </table>
         
          <input type="submit" class="btn btn-info" value="Guardar">
          <a class="btn btn-danger" href="{% url 'concepto_salario_list' %}">Cancelar</a>
      </form>
  </div>

{% endblock content %}

SICOS/templates/cirugia/honorario_form.html
{% extends 'base_cirugia.html' %}


{% block title %}
    Honorario
{% endblock title %}


{% block content %}

  <div class="jumbotron" width=20%>
      <form method="post" id="honor_form" data-proch-url="{% url 'lista_proc_ajax' %}"> 
          {% csrf_token %}
          <table>
              {{form.as_table}}
          </table>
         
          <input type="submit" class="btn btn-info" value="Guardar">
          <a class="btn btn-danger" href="{% url 'honorario_list' %}">Cancelar</a>
      </form>
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

  <script>
    $("#id_tipo_proc").change(function () {
      var url = $("#honor_form").attr("data-proch-url");  // get the url of the `load_cities` view
      var tipo_procId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'tipo_proc': tipo_procId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_procedimiento").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });
    });
  </script>


{% endblock content %}